#ifndef SELF_ASSEMBLY_MODELLING_ORIENTATION_H
#define SELF_ASSEMBLY_MODELLING_ORIENTATION_H

enum Orientation {
    ORIENTATION_NONE, ORIENTATION_VERTICAL, ORIENTATION_HORIZONTAL
};

#endif //SELF_ASSEMBLY_MODELLING_ORIENTATION_H
