#ifndef SELF_ASSEMBLY_MODELLING_ORIENTATION_H
#define SELF_ASSEMBLY_MODELLING_ORIENTATION_H

enum Orientation {
    NONE, VERTICAL, HORIZONTAL
};

#endif //SELF_ASSEMBLY_MODELLING_ORIENTATION_H
